from rest_framework import serializers
from cl.api.models import Webhook, WebhookEvent

class WebhookSerializer(serializers.ModelSerializer):
    class Meta:
        model = Webhook
        fields = [
            "id",
            "user",
            "event_type",
            "url",
            "enabled",
            "version",
            "failure_count",
            "date_created",
            "date_modified",
        ]
        read_only_fields = [
            "id",
            "user", # User should be set from request context, not directly by payload
            "failure_count",
            "date_created",
            "date_modified",
        ]

class WebhookEventSerializer(serializers.ModelSerializer):
    class Meta:
        model = WebhookEvent
        fields = [
            "id",
            "webhook",
            "event_id",
            "event_status",
            "content",
            "next_retry_date",
            "error_message",
            "response",
            "retry_counter",
            "status_code",
            "debug",
            "date_created",
            "date_modified",
        ]
        read_only_fields = [
            "id",
            "webhook", # Should be associated internally
            "event_id",
            "event_status",
            "content", # Assuming content is generated by the system
            "next_retry_date",
            "error_message",
            "response",
            "retry_counter",
            "status_code",
            "date_created",
            "date_modified",
        ]
